name: Feature request
description: Suggest an idea or enhancement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this useful?
    validations:
      required: true
